2023-07-17 09:24:38,437 ERROR frappe Failed to run after request hook
Site: site1.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5477717211256996489

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/app.py", line 143, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/auth.py", line 70, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/auth.py", line 119, in __init__
    self.make_session(resume=True)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/auth.py", line 207, in make_session
    frappe.local.session_obj = Session(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/sessions.py", line 238, in __init__
    self.resume()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/sessions.py", line 310, in resume
    validate_ip_address(self.user)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/auth.py", line 416, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1151, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1092, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1185, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/model/base_document.py", line 78, in get_controller
    return _get_controller()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/model/base_document.py", line 48, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 510, in get_value
    result = self.get_values(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 607, in get_values
    out = self._get_values_from_table(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 824, in _get_values_from_table
    query = frappe.qb.engine.get_query(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/query.py", line 515, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/query.py", line 371, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/query.py", line 330, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/query.py", line 196, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1497, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1462, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1418, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 975, in get_global
    return self.get_default(key, user)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 979, in get_default
    d = self.get_defaults(key, parent)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 995, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/defaults.py", line 239, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 202, in sql
    self.connect()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 116, in connect
    self._conn = self.get_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_e139a5fd5a72813a'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5477717211256996489

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1497, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1462, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1418, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 975, in get_global
    return self.get_default(key, user)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 979, in get_default
    d = self.get_defaults(key, parent)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 995, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/defaults.py", line 239, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 202, in sql
    self.connect()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 116, in connect
    self._conn = self.get_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_e139a5fd5a72813a'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5477717211256996489

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/app.py", line 84, in application
    response = handle_exception(e)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/app.py", line 338, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    frappe.log_error(f"{path} failed")
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 2239, in log_error
    error_log = get_doc(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1185, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/model/base_document.py", line 78, in get_controller
    return _get_controller()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/model/base_document.py", line 48, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 510, in get_value
    result = self.get_values(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 607, in get_values
    out = self._get_values_from_table(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 824, in _get_values_from_table
    query = frappe.qb.engine.get_query(
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/query.py", line 515, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/query.py", line 371, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/query.py", line 330, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/query.py", line 196, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1497, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1462, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1418, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 975, in get_global
    return self.get_default(key, user)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 979, in get_default
    d = self.get_defaults(key, parent)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 995, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/defaults.py", line 239, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 202, in sql
    self.connect()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 116, in connect
    self._conn = self.get_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_e139a5fd5a72813a'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5477717211256996489

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/app.py", line 98, in application
    run_after_request_hooks(request, response)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/app.py", line 114, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1497, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1462, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/__init__.py", line 1418, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 975, in get_global
    return self.get_default(key, user)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 979, in get_default
    d = self.get_defaults(key, parent)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 995, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/defaults.py", line 239, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/mohan/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 202, in sql
    self.connect()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/database.py", line 116, in connect
    self._conn = self.get_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/mohan/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/mohan/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_e139a5fd5a72813a'@'localhost' (using password: YES)")
